---
# Build Docker images using https://drone.io/ CI/CD and publish it to https://hub.docker.com/r/rspamd/
# Documentation http://plugins.drone.io/drone-plugins/drone-docker/ is not comprehensive
# Refer to the source: https://github.com/drone-plugins/drone-docker
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

x-default-settings: &default_settings
  username: { from_secret: docker_username }
  password: { from_secret: docker_password }
  storage_path: /drone/docker
  purge: false

x-versions:
  alpine: &alpine_version ALPINE_VERSION=3.17.0
  fedora: &fedora_version FEDORA_VERSION=37

steps:
- name: base_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-gcc/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-gcc/Dockerfile ]
    build_args: [ UBUNTU_VERSION=22.04 ]
    repo: rspamd/ci-ubuntu-gcc
    tags: [ latest, "22.04" ]

- name: build_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-build/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-build/Dockerfile ]
    repo: rspamd/ci-ubuntu-build
  depends_on: [ base_image ]

- name: test_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-test/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test/Dockerfile ]
    repo: rspamd/ci-ubuntu-test
  depends_on: [ build_image ]

- name: func_test_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-test-func/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test-func/Dockerfile ]
    repo: rspamd/ci-ubuntu-test-func
  depends_on: [ test_image ]

- name: perl_tidyall_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: perl-tidyall/Dockerfile
    label_schema: [ docker.dockerfile=perl-tidyall/Dockerfile ]
    build_args: [ *alpine_version ]
    repo: rspamd/ci-perl-tidyall

- name: fedora_build_image
  image: plugins/docker
  volumes:
  - name: fedora
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-build/Dockerfile
    label_schema: [ docker.dockerfile=fedora-build/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci-fedora-build

- name: fedora_test_image
  image: plugins/docker
  volumes:
  - name: fedora
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-test/Dockerfile
    label_schema: [ docker.dockerfile=fedora-test/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci-fedora-test
  depends_on: [ fedora_build_image ]

- name: centos8_pkg_image
  image: plugins/docker
  volumes:
  - name: centos8
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: centos-8/Dockerfile
    label_schema: [ docker.dockerfile=centos-8/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "centos-8" ]

- name: centos7_pkg_image
  image: plugins/docker
  volumes:
  - name: centos7
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: centos-7/Dockerfile
    label_schema: [ docker.dockerfile=centos-7/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "centos-7" ]

volumes:
- name: fedora
  temp: {}
- name: ubuntu
  temp: {}
- name: centos7
  temp: {}
- name: centos8
  temp: {}

trigger:
  branch: [ master ]
  event: [push, tag]
---
kind: signature
hmac: 0e55a1d5b76f7bf502bbba85a672007b9e57d34017b5804f5e1a55baf6ca4b94

...
