---
# Build Docker images using https://drone.io/ CI/CD and publish it to https://hub.docker.com/r/rspamd/
# Documentation http://plugins.drone.io/drone-plugins/drone-docker/ is not comprehensive
# Refer to the source: https://github.com/drone-plugins/drone-docker
kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

x-default-settings: &default_settings
  username: { from_secret: docker_username }
  password: { from_secret: docker_password }
  storage_path: /drone/docker
  purge: false

x-versions:
  alpine: &alpine_version ALPINE_VERSION=3.17.0
  fedora: &fedora_version FEDORA_VERSION=37

steps:
- name: base_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-gcc/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-gcc/Dockerfile ]
    build_args: [ UBUNTU_VERSION=22.04 ]
    repo: rspamd/ci
    tags: [ "ubuntu-gcc" ]

- name: build_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-build/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-build/Dockerfile ]
    repo: rspamd/ci
    tags: [ "ubuntu-build" ]
  depends_on: [ base_image ]

- name: test_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-test/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test/Dockerfile ]
    repo: rspamd/ci
    tags: [ "ubuntu-test" ]
  depends_on: [ build_image ]

- name: func_test_image
  image: plugins/docker
  volumes:
  - name: ubuntu
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-test-func/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test-func/Dockerfile ]
    repo: rspamd/ci
    tags: [ "ubuntu-test-func" ]
  depends_on: [ test_image ]

- name: perl_tidyall_image
  image: plugins/docker
  settings:
    <<: *default_settings
    dockerfile: perl-tidyall/Dockerfile
    label_schema: [ docker.dockerfile=perl-tidyall/Dockerfile ]
    build_args: [ *alpine_version ]
    repo: rspamd/ci
    tags: [ "perl-tidyall" ]

- name: fedora_build_image
  image: plugins/docker
  volumes:
  - name: fedora
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-build/Dockerfile
    label_schema: [ docker.dockerfile=fedora-build/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci
    tags: [ "fedora-build" ]

- name: fedora_test_image
  image: plugins/docker
  volumes:
  - name: fedora
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-test/Dockerfile
    label_schema: [ docker.dockerfile=fedora-test/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci
    tags: [ "fedora-test" ]
  depends_on: [ fedora_build_image ]

- name: centos8_pkg_image
  image: plugins/docker
  volumes:
  - name: centos8
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: centos-8/Dockerfile
    label_schema: [ docker.dockerfile=centos-8/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "centos-8" ]

- name: centos7_pkg_image
  image: plugins/docker
  volumes:
  - name: centos7
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: centos-7/Dockerfile
    label_schema: [ docker.dockerfile=centos-7/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "centos-7" ]

- name: ubuntu_jammy_pkg_image
  image: plugins/docker
  volumes:
  - name: ubuntu-jammy
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-jammy/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-jammy/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "ubuntu-jammy" ]
- name: ubuntu_focal_pkg_image
  image: plugins/docker
  volumes:
  - name: ubuntu-focal
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-focal/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-focal/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "ubuntu-focal" ]
- name: ubuntu_bionic_pkg_image
  image: plugins/docker
  volumes:
  - name: ubuntu-bionic
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: ubuntu-bionic/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-bionic/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "ubuntu-bionic" ]
- name: debian_bullseye_pkg_image
  image: plugins/docker
  volumes:
  - name: debian-bullseye
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: debian-bullseye/Dockerfile
    label_schema: [ docker.dockerfile=debian-bullseye/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "debian-bullseye" ]
- name: debian_buster_pkg_image
  image: plugins/docker
  volumes:
  - name: debian-buster
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: debian-buster/Dockerfile
    label_schema: [ docker.dockerfile=debian-buster/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "debian-buster" ]

- name: fedora37_pkg_image
  image: plugins/docker
  volumes:
  - name: fedora37
    path: /drone/docker
  settings:
    <<: *default_settings
    dockerfile: fedora-37/Dockerfile
    label_schema: [ docker.dockerfile=fedora-37/Dockerfile ]
    repo: rspamd/pkg
    tags: [ "fedora-37" ]

volumes:
- name: fedora
  temp: {}
- name: ubuntu
  temp: {}
- name: centos7
  temp: {}
- name: centos8
  temp: {}
- name: ubuntu-jammy
  temp: {}
- name: ubuntu-focal
  temp: {}
- name: ubuntu-bionic
  temp: {}
- name: debian-bullseye
  temp: {}
- name: debian-buster
  temp: {}
- name: fedora37
  temp: {}

trigger:
  branch: [ master ]
  event: [push, tag, custom]
---
kind: signature
hmac: 44ff9a72b8bc81c4d30cd4c1672c9e972aebf4e7baca8d641d9de478a743316c

...
