# Build Docker images using https://drone.io/ CI/CD and publish it to https://hub.docker.com/r/rspamd/
---
pipeline:

  base_image:
    image: plugins/docker
    dockerfile: ubuntu-gcc/Dockerfile
    label_schema: [ docker.dockerfile="ubuntu-gcc/Dockerfile" ]
    repo: rspamd/ci-ubuntu-gcc
    # Use current LTS release (Bionic Beaver)
    build_args:
      - UBUNTU_VERSION=18.04
    tags:
      - latest
      - 18.04
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]

  build_image:
    image: plugins/docker
    dockerfile: ubuntu-build/Dockerfile
    repo: rspamd/ci-ubuntu-build
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]

  test_image:
    image: plugins/docker
    dockerfile: ubuntu-test/Dockerfile
    repo: rspamd/ci-ubuntu-test
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]

  func_test_image:
    image: plugins/docker
    dockerfile: ubuntu-test-func/Dockerfile
    repo: rspamd/ci-ubuntu-test-func
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, tag]
