# Build Docker images using https://drone.io/ CI/CD and publish it to https://hub.docker.com/r/rspamd/
# Documentation http://plugins.drone.io/drone-plugins/drone-docker/ is not comprehensive
# Refer to the source: https://github.com/drone-plugins/drone-docker
---
x-defaults: &defaults
    image: plugins/docker
    storage_path: /drone/docker
    secrets: [ docker_username, docker_password ]
    purge: false
    when:
      event: [push, tag]

x-versions:
  fedora: &fedora_version FEDORA_VERSION=29

pipeline:
  base_image:
    <<: *defaults
    pull: true
    dockerfile: ubuntu-gcc/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-gcc/Dockerfile ]
    repo: rspamd/ci-ubuntu-gcc
    # Use current LTS release (Bionic Beaver)
    build_args: [ UBUNTU_VERSION=18.04 ]
    tags: [ latest, "18.04" ]

  build_image:
    <<: *defaults
    # based on rspamd/ci-ubuntu-gcc
    dockerfile: ubuntu-build/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-build/Dockerfile ]
    repo: rspamd/ci-ubuntu-build

  test_image:
    <<: *defaults
    # based on rspamd/ci-ubuntu-gcc
    dockerfile: ubuntu-test/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test/Dockerfile ]
    repo: rspamd/ci-ubuntu-test

  func_test_image:
    <<: *defaults
    # based on rspamd/ci-ubuntu-test
    dockerfile: ubuntu-test-func/Dockerfile
    label_schema: [ docker.dockerfile=ubuntu-test-func/Dockerfile ]
    repo: rspamd/ci-ubuntu-test-func

  perl_tidyall_image:
    <<: *defaults
    # based on apline:3.8
    dockerfile: perl-tidyall/Dockerfile
    label_schema: [ docker.dockerfile=perl-tidyall/Dockerfile ]
    repo: rspamd/ci-perl-tidyall

  fedora_build_image:
    <<: *defaults
    dockerfile: fedora-build/Dockerfile
    label_schema: [ docker.dockerfile=fedora-build/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci-fedora-build

  fedora_test_image:
    <<: *defaults
    dockerfile: fedora-test/Dockerfile
    label_schema: [ docker.dockerfile=fedora-test/Dockerfile ]
    build_args: [ *fedora_version ]
    repo: rspamd/ci-fedora-test
